export const WEATHER_CONDITIONS = [
  {
    code: 1000,
    day: "Sunny",
    night: "Clear",
    icon: "weather-sunny",
  },
  {
    code: 1003,
    day: "Partly cloudy",
    night: "Partly cloudy",
    icon: "weather-cloudy",
  },
  {
    code: 1006,
    day: "Cloudy",
    night: "Cloudy",
    icon: "weather-cloudy",
  },
  {
    code: 1009,
    day: "Overcast",
    night: "Overcast",
    icon: "weather-cloudy",
  },
  {
    code: 1030,
    day: "Mist",
    night: "Mist",
    icon: "weather-cloudy",
  },
  {
    code: 1063,
    day: "Patchy rain possible",
    night: "Patchy rain possible",
    icon: "weather-partly-rainy",
  },
  {
    code: 1087,
    day: "Thundery outbreaks possible",
    night: "Thundery outbreaks possible",
    icon: "weather-lightning-rainy",
  },
  {
    code: 1150,
    day: "Patchy light drizzle",
    night: "Patchy light drizzle",
    icon: "weather-rainy",
  },
  {
    code: 1153,
    day: "Light drizzle",
    night: "Light drizzle",
    icon: "weather-rainy",
  },
  {
    code: 1180,
    day: "Patchy light rain",
    night: "Patchy light rain",
    icon: "weather-rainy",
  },
  {
    code: 1183,
    day: "Light rain",
    night: "Light rain",
    icon: "weather-rainy",
  },
  {
    code: 1186,
    day: "Moderate rain at times",
    night: "Moderate rain at times",
    icon: "weather-rainy",
  },
  {
    code: 1189,
    day: "Moderate rain",
    night: "Moderate rain",
    icon: "weather-rainy",
  },
  {
    code: 1192,
    day: "Heavy rain at times",
    night: "Heavy rain at times",
    icon: "weather-rainy",
  },
  {
    code: 1195,
    day: "Heavy rain",
    night: "Heavy rain",
    icon: "weather-rainy",
  },
  {
    code: 1222,
    day: "Patchy heavy snow",
    night: "Patchy heavy snow",
    icon: 335,
  },
  {
    code: 1240,
    day: "Light rain shower",
    night: "Light rain shower",
    icon: "weather-rainy",
  },
  {
    code: 1243,
    day: "Moderate or heavy rain shower",
    night: "Moderate or heavy rain shower",
    icon: "weather-rainy",
  },
  {
    code: 1246,
    day: "Torrential rain shower",
    night: "Torrential rain shower",
    icon: "weather-rainy",
  },
  {
    code: 1273,
    day: "Patchy light rain with thunder",
    night: "Patchy light rain with thunder",
    icon: "weather-lightning-rainy",
  },
  {
    code: 1276,
    day: "Moderate or heavy rain with thunder",
    night: "Moderate or heavy rain with thunder",
    icon: "weather-lightning-rainy",
  },
];
